dependencies:
  - any: ["package.json", "yarn.lock"]

frontend:
  - any: ["src/**/*.{ts,tsx}", "public/**/*", "style/**/*.{css,scss}", "lib/**/*.{ts,tsx}"]

config:
  - any: ["*.config.js", "*.config.mjs", "tsconfig.json", ".prettierrc", ".yarnrc.yml", ".gitignore"]

github-actions:
  - any: [".github/**/*"]

docs:
  - any: ["**/*.md", "README.md"]
