dependencies:
  - "package.json"
  - "yarn.lock"

frontend:
  - "src/**/*.{ts,tsx}"
  - "public/**/*"
  - "style/**/*.{css,scss}"
  - "lib/**/*.{ts,tsx}"

config:
  - "*.config.js"
  - "*.config.mjs"
  - "tsconfig.json"
  - ".prettierrc"
  - ".yarnrc.yml"
  - ".gitignore"

github-actions:
  - ".github/**/*"

docs:
  - "**/*.md"
  - "README.md"
